### ISSUE TITLE
Calendar/Contact Sync on WP

### ISSUE THREAD

**Issue by wf-r** [owncloud-archive/windows-phone#15]
Hi,
this might be interesting for you:
I just found this manual for syncing your WP with OwnCloud/other CalDav-Calendars: http://stadt-bremerhaven.de/windows-phone-update-bringt-caldav-und-carddav-fuer-die-synchronisation-mit-google-daten/#comment-373275
Basically you just create a new Google Account, restart your phone and (while the account is not syncing) put in the right CalDav/CardDav adresses

**Comment by framedynamic** [comment]
Outdated.
