### ISSUE TITLE
Connection with sockets

### ISSUE THREAD

**Issue by Ahn1** [owncloud-archive/windows-phone#2]
Hello,

i saw you created a own TLS/Sockets Implementation.

Is this necessary because windows phone does not really support https?

If this sould be true, i have to use this too...
I've used the default HttpWebRequest now.

**Comment by framedynamic** [comment]
That is not a full TLS implementation, it is only a handshake to fetch the certificate to show to the user as a feature.

The phone actually supports TLS but the HttpWebRequest class will reject a self signed certificate as non valid if the certificate is not in trusted storage or the issuer is non of the root ca's installed on the phone.

The class will fail with the insignificant message "Not found" but in fact rejects the server certificate.
