### ISSUE TITLE
How can I build a WPF windows desktop version from this code

### ISSUE THREAD

**Issue by tobitech** [owncloud-archive/windows-phone#25]
I want to build a windows desktop version of the owncloud. I'm not comfortable with the fact that the desktop client source code available on GitHub isn't available in C#. So I am thinking of using the code to develop a WPF version of the owncloud client for windows desktop. All forms of helpful suggestions would be welcomed.

**Comment by framedynamic** [comment]
This isn't an issue for this project but we're going on maybe on Windows10 UAP in future.
