### ISSUE TITLE
DAV structure was not recognized. Please check the server paths

### ISSUE THREAD

**Issue by tobitech** [owncloud-archive/windows-phone#26]
I just got the OwnCloud Windows Phone verison from GitHub, I am trying to use the App, while trying to add an account, I'm required to enter a WebDAV, I didn't know what this mean until I searched online, and I thought I could just replace the owncloud client in the default with our owncloud web url which I entered into the Host, but from the app I am getting an error saying DAV structure was not recognized. Please check the server paths. Server answer: method not allowed

**Comment by Faldon** [comment]
In a standard ownCloud installation, the WebDAV path should be http[s]://your.server.name/remote.php/webdav/ where your.server.name would be the url you'd enter to access your ownCloud via browser.

**Comment by framedynamic** [comment]
I think this can be closed.
